export const BOLLYWOOD_MOVIES = {
    "action": [
    "Don",
    "Dhoom",
    "War",
    "Bang Bang",
    "Singham",
    "Krrish",
    "Tiger Zinda Hai",
    "Pathaan",
    "Ra.One",
    "Baaghi",
    "Jawan",
    "Tiger 3",
    "Singham Again",
    "Sky Force",
    "Jaat",
    "Bade Miyan Chote Miyan",
    "Ground Zero",
    "Raaz 2",
    "Force 3",
    "Race 4",
    "Krrish 4",
    "Baaghi 4",
    "Satyamev Jayate 3",
    "War 2",
    "Dhoom 4",
    "Don 3",
    "Shershaah 2",
    "Uri 2",
    "Kesari 2",
    "Commando 4",
    "Bajirao Mastani 2",
    "Lagaan 2",
    "Jolly LLB 3",
    "Raees 2",
    "Kahaani 3",
    "Don 4",
    "Sultan 2",
    "Kick 2",
    "Baazigar 2",
    "Andhadhun 2",
    "Drishyam 3",
    "Kesari Chapter 2",
    "The Bhootnii",
    "The Great Indian Rescue",
    "Mission Kashmir",
    "Operation Blue Star",
    "Border 2",
    "Surgical Strike 2"
  ],
    "romance": [
    "Dilwale Dulhania Le Jayenge",
    "Kuch Kuch Hota Hai",
    "Jab We Met",
    "Veer-Zaara",
    "Yeh Jawaani Hai Deewani",
    "Kabhi Khushi Kabhie Gham",
    "Dil To Pagal Hai",
    "Mohabbatein",
    "Kal Ho Naa Ho",
    "Devdas",
    "Loveyapa",
    "Bhool Chuk Maaf",
    "Mere Husband Ki Biwi",
    "Dil Dhadakne Do",
    "Tamasha",
    "Ae Dil Hai Mushkil",
    "Barfi",
    "Tanu Weds Manu",
    "Jab Tak Hai Jaan",
    "Pyaar Ka Punchnama",
    "Aashiqui 2",
    "Sanam Teri Kasam",
    "Pati Patni Aur Woh",
    "Kedarnath",
    "Sui Dhaaga",
    "Laila Majnu",
    "Meri Pyaari Bindu",
    "Ek Villain",
    "Half Girlfriend",
    "Badrinath Ki Dulhania",
    "Raabta",
    "Jab Harry Met Sejal",
    "Sultan",
    "Dhadak",
    "Love Aaj Kal",
    "Mujhse Dosti Karoge",
    "Saathiya",
    "Vivah",
    "Hum Dil De Chuke Sanam",
    "Rehnaa Hai Terre Dil Mein",
    "Hum Tum",
    "Kabhi Alvida Naa Kehna"
  ],
  default: [
    "Inception",
    "The Dark Knight",
    "Interstellar",
    "Avengers: Endgame",
    "Avengers: Infinity War",
    "Titanic",
    "Avatar",
    "Forrest Gump",
    "The Godfather",
    "The Godfather: Part II",
    "Pulp Fiction",
    "The Matrix",
    "Gladiator",
    "Jurassic Park",
    "Fight Club",
    "The Shawshank Redemption",
    "The Lord of the Rings: The Return of the King",
    "Iron Man",
    "Captain America: Civil War",
    "Black Panther",
    "Doctor Strange",
    "Spider-Man: No Way Home",
    "Oppenheimer",
    "Barbie",
    "Everything Everywhere All At Once",
    "Mission: Impossible – Fallout",
    "Top Gun: Maverick",
    "Dune",
    "The Prestige",
    "The Revenant",
    "No Time to Die",
    "3 Idiots",
    "PK",
    "Dangal",
    "Lagaan",
    "Bajrangi Bhaijaan",
    "Andhadhun",
    "Gully Boy",
    "Barfi",
    "Zindagi Na Milegi Dobara",
    "Article 15",
    "Piku",
    "Chhichhore",
    "Taare Zameen Par",
    "Queen"
  ],


  }

